matrix_chain_multiplication_usingdp.cpp

i did my job 😊. please merge it , Thank You.

matrix chain multiplication using DP

---

Knapsack.cpp

0-1 knapsack problem

---

Knapsack_problem.cpp

Created Knapsack_problem.cpp . Issue no #22

Created Knapsack_problem.cpp . Issue no #22

---

Subset_Sum_Problem.cpp

Solved Issue no #25

---

LongestPalindromicSubsequence.cpp

Longest Palindromic Subsequence using recursion and memoisation method

LongestPalindromicSubsequence using dp

---

Algorithm/EuclidAlgorithm.cpp

Please Check this Euclid Algorithms Code in Algorithm branch and Merge it

Added EuclidAlgorithm to Algorithms Folder

---

Algorithm/SelectionSort.cpp

Could you pls review my pr and also do inform me if you need any changes.

Added Selection Sort in Algorithm folder

---

Algorithm/Floyd_Warshall_Algorithm.cpp

Please accept my PR under the label of hacktoberfest-accepted. Thankyou :)

created Floyd Warshall Algorithm

---

Algorithm/Topologicalsort.cpp

algorithm and code for topological sort

Topologicalsort.cpp

---

Algorithm/Quick_Sort.cpp
Algorithm/Union_Find_Algorithm.cpp

Please accept my PR under the label of hacktoberfest-accepted.  Thankyou :)

Created Quick Sort Algorithm

---

Algorithm/KruskalsAlgorithm.cpp

Added Kruskal's Algorithm

---

Algorithm/Boyer_Moore_Majority_Voting_Algorithm.cpp

**Closes Issue #80**
I have implemented the Boyer Moore Voting Algorithm in C++ and added the file Boyer_Moore_Majority_Voting_Algorithm.cpp in Algorithm Folder in the repo.
Please do let me know if I need to change anything.

Code and Explanation of Boyer Moore Voting Algorithm

---

Algorithm/KMP_Algorithm.cpp

Added KMP Algorithm

---

Algorithm/HeapSortAlgorithm.cpp

Added Heap Sort Algorithm implemented in C++

Uploaded Heap Sort Algo

---

Algorithm/BellmanFordAlgorithm.cpp

Bellman Ford Algorithm Added

---

Algorithm/Depth_First_Search.cpp

Assigned Issue: Depth First Search (DFS) Algorithm #58

added the code for Depth First Search in cpp

---

Algorithm/Kadanes_Algorithm.cpp

**CLOSES ISSUE #65**
I have written the code with proper explanation for Kadane's Algorithm and saved it as Kadanes_Algorithm.cpp in the Algorithm folder. 
Please let me know if I need to make any changes to it. Thank you!

Added Kadane's Algorithm with proper explanation in the Algorithm Folder

---

Algorithm/Breadth_First_Search_Algorithm.cpp

**Closes Issue #57**
I have implemented the Breadth First Search Algorithm in C++ and added the file  Breadth_First_Search_Algorithm.cpp in Algorithm Folder in the repo.
Please do let me know if I need to change anything.

Code and Explanation of Breadth First Search Algorithm

---

Algorithm/FloodFillAlgorithm.cpp

Added Flood Fill Algorithm

---

Water_Jug.cpp

I have added the Water Jug Problem Code in C++
https://github.com/raunakkumarsingh/Cpp_Code/issues/47

Added the new file for the Water Jug program in C++

---

3partition.cpp

i have written the code. hope it helps you

3 partition problem

---

boxstack.cpp

i have written the code. hope it helps you

box stack problem

---

Vivek Kumar

Kth max and min term of an array.

Added a code.
